import os
from typing import Any

import chromadb
from dotenv import load_dotenv

from config.settings import PROJECT_ROOT, BATCH_SIZE, DEFAULT_COLLECTION

def configure_chroma_env() -> None:
    """Load .env and map project-specific variable names to Chroma's expected names."""
    load_dotenv(PROJECT_ROOT / ".env")

    mappings = {
        "CHROMA_API_KEY": ("CHROMADB_API_KEY", "CHROMA_API_KEY"),
        "CHROMA_TENANT": ("CHROMA_DB_TENANT", "CHROMA_TENANT"),
        "CHROMA_DATABASE": ("CHROMA_DB_DATABASE", "CHROMA_DATABASE"),
    }

    for target, sources in mappings.items():
        if os.getenv(target):
            continue
        for source in sources:
            value = os.getenv(source)
            if value:
                os.environ[target] = value
                break


class ChromaInventoryStore:
    """Batch-oriented Chroma Cloud store for Genesis vehicle documents."""

    def __init__(
        self,
        collection_name: str | None = None,
        batch_size: int = BATCH_SIZE,
    ) -> None:
        configure_chroma_env()
        self.batch_size = batch_size
        self.collection_name = collection_name or os.getenv(
            "CHROMA_COLLECTION",
            DEFAULT_COLLECTION,
        )
        self.client = chromadb.CloudClient(
            tenant=os.getenv("CHROMA_TENANT"),
            database=os.getenv("CHROMA_DATABASE"),
            api_key=os.getenv("CHROMA_API_KEY"),
        )
        # Use the collection's persisted Chroma default embedding function.
        # Documents are embedded server-side; we never pass local vectors.
        self.collection = self.client.get_or_create_collection(
            name=self.collection_name,
            metadata={"source": "genesis_cpo_scraper"},
        )

    @staticmethod
    def _chunk(items: list[Any], size: int) -> list[list[Any]]:
        return [items[i : i + size] for i in range(0, len(items), size)]

    def upsert_items(self, ingestion_items: list[dict[str, Any]]) -> int:
        """Embed via Chroma Cloud and upsert documents with metadata in batches."""
        if not ingestion_items:
            return 0

        total = 0
        for batch in self._chunk(ingestion_items, self.batch_size):
            ids = [item["id"] for item in batch]
            documents = [item["text"] for item in batch]
            metadatas = [item["metadata"] for item in batch]

            # Embeddings are generated by Chroma Cloud; do not pass local vectors.
            self.collection.upsert(
                ids=ids,
                documents=documents,
                metadatas=metadatas,
            )
            total += len(batch)

        return total

    def delete_items(self, car_ids: list[str]) -> int:
        """Remove sold or delisted vehicles from the collection."""
        if not car_ids:
            return 0

        total = 0
        for batch in self._chunk(car_ids, self.batch_size):
            self.collection.delete(ids=batch)
            total += len(batch)

        return total

    def sync_inventory_delta(self, delta_result: dict[str, Any]) -> dict[str, int]:
        """
        Apply a delta result from delta_worker.process_scrape_result to Chroma.
        Returns counts for observability and logging.
        """
        upserted = self.upsert_items(delta_result.get("ingestion_items", []))

        deleted_ids = [
            str(car["id"])
            for car in delta_result.get("deletions", [])
            if car.get("id")
        ]
        deleted = self.delete_items(deleted_ids)

        return {
            "upserted": upserted,
            "deleted": deleted,
            "is_first_run": int(bool(delta_result.get("is_first_run"))),
        }

def sync_delta_to_chroma(delta_result: dict[str, Any]) -> dict[str, int]:
    """Convenience wrapper used by the scraper orchestration."""
    store = ChromaInventoryStore()
    return store.sync_inventory_delta(delta_result)
